import { useEffect, useState } from "react";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { repoFor, loadRepoChunk } from "@/lib/files";
import { RepoHeader, LanguageBar, FileListing, CommitList, formatBytes } from "./RepoParts";
import ContributionGraph from "./ContributionGraph";
import ReadmeView from "./ReadmeView";

/**
 * A GitHub repository page.
 *
 * Metadata (header, languages, file list, commits, graph) ships in the main
 * bundle. The README and per-file source live in a per-repo chunk that is
 * dynamically imported when this mounts, so opening one repo does not pull the
 * other ten.
 */
export default function RepoView({ file }) {
  const repo = repoFor(file);

  const [chunk, setChunk] = useState(null);
  const [state, setState] = useState("loading");
  const [openFile, setOpenFile] = useState(null);

  useEffect(() => {
    let cancelled = false;
    setState("loading");
    setOpenFile(null);

    loadRepoChunk(repo.repo)
      .then((data) => {
        if (cancelled) return;
        setChunk(data);
        setState("ready");
      })
      .catch(() => {
        if (!cancelled) setState("error");
      });

    return () => {
      cancelled = true;
    };
  }, [repo.repo]);

  if (openFile) {
    return (
      <SourceView
        repo={repo}
        name={openFile}
        source={chunk?.sources?.[openFile]}
        onBack={() => setOpenFile(null)}
      />
    );
  }

  return (
    <div className="doc-wide">
      <RepoHeader repo={repo} />
      <LanguageBar languages={repo.languageBar} />

      <FileListing
        repo={repo}
        onOpenFile={chunk?.sources ? setOpenFile : null}
        activeFileName={null}
      />

      <section aria-label="Commit activity" className="pb-8">
        <h2 className="t-h3 mb-3">Commit activity</h2>
        <div className="rounded-[6px] border border-vs-border px-5 py-4">
          <ContributionGraph
            days={repo.contributions?.days}
            total={repo.contributions?.total}
            compact
          />
        </div>
      </section>

      <CommitList commits={repo.commits} repo={repo} />

      {state === "loading" ? (
        <p className="t-small pb-10 text-vs-descr">Loading README…</p>
      ) : state === "error" ? (
        <p className="t-small pb-10 text-vs-descr">
          README unavailable offline.{" "}
          <a
            href={repo.htmlUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="text-vs-accent hover:underline"
          >
            Read it on GitHub
          </a>
        </p>
      ) : (
        <ReadmeView markdown={chunk?.readme} />
      )}
    </div>
  );
}

/**
 * One file's source, pre-highlighted by Shiki at build time — the markup is
 * inserted as-is because it was generated by our own build, never from user
 * input at runtime.
 */
function SourceView({ repo, name, source, onBack }) {
  if (!source) {
    return (
      <div className="doc-wide">
        <BackBar name={name} repo={repo} onBack={onBack} />
        <p className="t-small mt-4 text-vs-descr">
          Source for this file was not included in the build.
        </p>
      </div>
    );
  }

  return (
    <div className="doc-wide">
      <BackBar name={name} repo={repo} onBack={onBack} lines={source.lines} bytes={source.bytes} />
      <div
        className="mt-3 overflow-hidden rounded-[6px] border border-vs-border py-3"
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: source.html }}
      />
    </div>
  );
}

function BackBar({ name, repo, onBack, lines, bytes }) {
  return (
    <div className="flex flex-wrap items-center gap-3 border-b border-vs-border pb-3">
      <button
        type="button"
        onClick={onBack}
        className="flex items-center gap-1.5 text-[13px] text-vs-accent hover:underline"
      >
        <ArrowLeft className="h-4 w-4" strokeWidth={1.7} />
        {repo.repo}
      </button>
      <span className="text-vs-descr">/</span>
      <span className="text-[13px] text-vs-text">{name}</span>
      {lines ? (
        <span className="text-[12px] text-vs-descr">
          {lines} lines · {formatBytes(bytes)}
        </span>
      ) : null}
      <a
        href={`${repo.htmlUrl}/blob/${repo.defaultBranch}/${name}`}
        target="_blank"
        rel="noopener noreferrer"
        className="ml-auto flex items-center gap-1.5 text-[12.5px] text-vs-descr hover:text-vs-text"
      >
        <ExternalLink className="h-[13px] w-[13px]" strokeWidth={1.6} />
        View on GitHub
      </a>
    </div>
  );
}
